commander:
  extends:
    file: ./commander/compose.yml
    service: commander
  environment:
    - REDIS=true
  ports:
    - "8888:8888"
  links:
    - redis
    - registry:coregistry
    - engine:buildengine
registry:
  extends:
    file: ./registry/compose.yml
    service: registry
  ports:
      - 5000:5000
  volumes:
    - /var/lib/registry
    - /certs
    - /auth
engine:
  extends:
    file: ./engine/compose.yml
    service: engine
  links:
    - registry:coregistry
redis:
  image: redis:3
