forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-apt',
  :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod 'puppetlabs-stdlib',
  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

mod 'puppetlabs-concat',
  :git => "git://github.com/puppetlabs/puppetlabs-concat.git"

mod 'puppetlabs-apache',
  :git => "git://github.com/puppetlabs/puppetlabs-apache.git"
