engine:
  image: cloudopting/craneengine
  privileged: true
  volumes:
    - /var/lib/docker
    - /lib/modules:/lib/modules
    - ./certs:/var/lib/coengine/certs
  hostname: coengine
  environment:
    - DOCKER_DAEMON_ARGS=--tlsverify --tlscacert=/var/lib/coengine/certs/ca.pem --tlscert=/var/lib/coengine/certs/server-cert.pem --tlskey=/var/lib/coengine/certs/server-key.pem
    - PORT=4243
