engine:
  build: .
  privileged: true
  volumes:
    - /var/lib/docker
    - /lib/modules:/lib/modules
    - ./certs:/var/lib/coengine/certs
  hostname: coengine
  environment:
    - DOCKER_DAEMON_ARGS=--tlsverify --tlscacert=/var/lib/coengine/certs/ca.pem --tlscert=/var/lib/coengine/certs/server-cert.pem --tlskey=/var/lib/coengine/certs/server-key.pem -s devicemapper  --storage-opt dm.loopdatasize=200G --storage-opt dm.override_udev_sync_check=true
    - PORT=4243
