forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-apt',
  :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod 'puppetlabs-stdlib',
  :git => "https://github.com/puppetlabs/puppetlabs-stdlib"

mod 'puppetlabs-concat',
  :git => "https://github.com/puppetlabs/puppetlabs-concat"

mod 'puppetlabs-apache',
  :git => "git://github.com/puppetlabs/puppetlabs-apache.git"

